project:
  type: website
  output-dir: docs

website:
  title: "Bimandra Djaafara"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer: "Copyright 2024 &copy; Bimandra Djaafara"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
