project:
  type: website
  resources:
    - CNAME
  output-dir: docs

execute:
    freeze: auto

website:
  title: "Bimandra Djaafara"
  navbar:
    background: primary
    right:
      - href: news.qmd
        text: News
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact
  page-footer: "Copyright 2024 &copy; Bimandra Djaafara"
  google-analytics: "G-K5TXS64QLN"
  site-url: https://andradjaafara.github.io
  repo-url: https://github.com/andradjaafara/andradjaafara.github.io

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
