project:
  type: website
  output-dir: docs

website:
  title: "Bimandra Djaafara (Andra)"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
  page-footer: "&copy; 2024"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
