project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/**/*.qmd"
    - "!claude.md"

website:
  title: "Bimandra Djaafara (Andra)"
  site-url: https://andradjaafara.github.io
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: Updates
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - href: cv-short.pdf
        text: CV
  page-footer: "&copy; 2026 Bimandra Djaafara | [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"

format:
  html:
    theme: litera
    css: styles.css
    toc: true
