project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/**/*.qmd"
    - "!claude.md"

website:
  title: "Bimandra Djaafara (Andra)"
  site-url: https://andradjaafara.github.io
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: News
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - href: resources.qmd
        text: Resources
  page-footer: "&copy; 2025 Bimandra Djaafara"

format:
  html:
    theme: litera
    css: styles.css
    toc: true
